### ISSUE TITLE
[ Enhancement ] Add support for TimeZones in FS operations

### ISSUE THREAD

**Issue by YourWishes** [blocksds/libnds#87]
Hello, please refer to this ongoing discussion;
https://github.com/DS-Homebrew/TWiLightMenu/issues/2360

Currently TWiLightMenu is using libfat for their FS operations, but are considering replacing with libnds FS operations. A current bug on the DSi firmware is a lack of TimeZone, and FS operations are assuming the time is set to UTC+0. This causes file timestamps to drift by the value of whatever the timezone the user is in, e.g. if I am in UTC+10:00 then when I save a file it will appear to have been saved 10 hours in the future from the actual time it was saved.

Just opening the conversation at this point, perhaps either extending `rtcTimeAndDate` struct or creating a new `rtcTimeAndDateWithTimeZone` struct could work instead. Alternatively adding some FILE operations that can take consideration of timezone(s), as I think this is one of the only affected areas.

**Comment by AntonioND** [comment]
Hi! Can you re-open this issue here? https://github.com/blocksds/sdk Just so that everything is centralized.
